image: docker:latest

stages:
  - build_docker_image
  - publish

cache:
  key: "$CI_JOB_NAME-$CI_COMMIT_REF_SLUG"
  paths:
    - /root/.m2

build_docker_image_latest:
  stage: build_docker_image
  tags:
    - docker
    - shell
  only:
    - master
  script:
    - docker build --pull -t ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA} .

build_docker_image_tags:
  stage: build_docker_image
  tags:
    - docker
    - shell
  only:
    - tags
  script:
    - docker build --pull -t ${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG} .

publish_latest:
  stage: publish
  tags:
    - docker
    - shell
  only:
    - master
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker push ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA}
    - docker tag ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA} ${CI_REGISTRY_IMAGE}:latest
    - docker push ${CI_REGISTRY_IMAGE}:latest

publish_tags:
  stage: publish
  tags:
    - docker
    - shell
  only:
    - tags
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    # full alias
    - docker push ${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG}
    # tag and push aliases
    # short alias (eg.: "6")
    - docker tag ${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG} ${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG%%.*}
    - docker push ${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG%%.*}
    # long alias (eg.: "6.2")
    - docker tag ${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG} ${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG%.*}
    - docker push ${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG%.*}